#preload = ~/Pictures/wallpapers/mi_background.jpg
#wallpaper = eDP-1,~/Pictures/wallpapers/mi_background.jpg
#splash = false

wallpaper {
    monitor = eDP-1
    path = /home/markie/Pictures/wallpapers/mi_background.jpg
    fit_mode = cover
}

splash = false
